export const getData =
  [
    {
      "id":1,
      "name":"佐藤テスト",
      "gender":"男",
      "position":"社長",
      "joining_day":"1998/04/01",
      "birthday":"1960/06/23",
      "age":"60",
      "school_career":"〇〇大学",
      "phone_number":"080-1122-3344",
      "near_station":"〇〇駅",
      "company_id":"データウェアネットワーク株式会社",
      "area_id":"中部",
      "occupation_id":"SE",
      "employment_system_id":"ディレクター"
    },
    {
      "id":2,
      "name":"星井千代子",
      "gender":"女",
      "position":"パート",
      "joining_day":"2019/04/07",
      "birthday":"1996/02/14",
      "age":"23",
      "school_career":"☆☆大学",
      "phone_number":"080-5566-7788",
      "near_station":"☆☆駅",
      "company_id":"データウェアネットワーク株式会社",
      "area_id":"関東",
      "occupation_id":"事務職",
      "employment_system_id":"サポート"
    },
  ];