export const getData =
  [
    {
      "id":1,
      "staff_id":1,
      "name":"ABC開発プロジェクト",
      "number_of_persons":"1",
      "matter_start":"2020/07/01",
      "matter_end":"2020/08/10",
      "business_content":"ABC開発の案件です。",
      "note":"備考",
      "name_2":"SE",
    },
    {
        "id":2,
        "staff_id":2,
        "name":"123開発プロジェクト",
        "number_of_persons":"10",
        "matter_start":"2020/07/01",
        "matter_end":"2020/08/10",
        "business_content":"123開発の案件です。",
        "note":"備考",
        "name_2":"PE",
    },
  ];