export const getData = [
    {
        "id":1,
        "name":"佐藤テスト",
        "position":"社長",
        "company_abbreviation":"DWS",
        "matter_end":"2020-08-31"
    },
    {
        "id":2,
        "name":"佐藤テスト",
        "position":"社長",
        "company_abbreviation":"DWS",
        "matter_end":"2020-08-31"
    },
    {
        "id":3,
        "name":"佐藤テスト",
        "position":"社長",
        "company_abbreviation":"DWS",
        "matter_end":"2020-08-31"
    },
    {
        "id":4,
        "name":"佐藤テスト",
        "position":"社長",
        "company_abbreviation":"DWS",
        "matter_end":"2020-08-31"
    },
    {
        "id":5,
        "name":"佐藤テスト",
        "position":"社長",
        "company_abbreviation":"DWS",
        "matter_end":"2020-08-31"
    },
]