export const getData = [
    {
        "id":1,
        "name":"佐藤テスト",
        "position":"社長",
        "company_abbreviation":"DWS",
        "matter_end":"2020-10-30"
    },
    {
        "id":2,
        "name":"後藤テスト",
        "position":"課長",
        "company_abbreviation":"DWS",
        "matter_end":"2020-11-29"
    },
    {
        "id":3,
        "name":"菊池テスト",
        "position":"部長",
        "company_abbreviation":"DWS",
        "matter_end":""
    },
    {
        "id":4,
        "name":"磯野テスト",
        "position":"プロデューサー",
        "company_abbreviation":"DWS",
        "matter_end":""
    },
    {
        "id":5,
        "name":"鈴木テスト",
        "position":"プロデューサー",
        "company_abbreviation":"SAN",
        "matter_end":"2020-12-09"
    },
]